-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 22:04:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbdotproject_g6
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbdotproject_g6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbdotproject_g6` DEFAULT CHARACTER SET utf8mb4 ;
USE `dbdotproject_g6` ;

-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_projects` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_company` INT(11) NOT NULL DEFAULT 0,
  `project_company_internal` INT(11) NOT NULL DEFAULT 0,
  `project_department` INT(11) NOT NULL DEFAULT 0,
  `project_name` VARCHAR(255) NULL DEFAULT NULL,
  `project_short_name` VARCHAR(10) NULL DEFAULT NULL,
  `project_owner` INT(11) NULL DEFAULT 0,
  `project_url` VARCHAR(255) NULL DEFAULT NULL,
  `project_demo_url` VARCHAR(255) NULL DEFAULT NULL,
  `project_start_date` DATETIME NULL DEFAULT NULL,
  `project_end_date` DATETIME NULL DEFAULT NULL,
  `project_status` INT(11) NULL DEFAULT 0,
  `project_percent_complete` TINYINT(4) NULL DEFAULT 0,
  `project_color_identifier` VARCHAR(6) NULL DEFAULT 'eeeeee',
  `project_description` TEXT NULL DEFAULT NULL,
  `project_target_budget` DECIMAL(10,2) NULL DEFAULT 0.00,
  `project_actual_budget` DECIMAL(10,2) NULL DEFAULT 0.00,
  `project_creator` INT(11) NULL DEFAULT 0,
  `project_private` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `project_departments` CHAR(100) NULL DEFAULT NULL,
  `project_contacts` CHAR(100) NULL DEFAULT NULL,
  `project_priority` TINYINT(4) NULL DEFAULT 0,
  `project_type` SMALLINT(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`project_id`),
  INDEX `idx_project_owner` (`project_owner` ASC) VISIBLE,
  INDEX `idx_sdate` (`project_start_date` ASC) VISIBLE,
  INDEX `idx_edate` (`project_end_date` ASC) VISIBLE,
  INDEX `project_short_name` (`project_short_name` ASC) VISIBLE,
  INDEX `idx_proj1` (`project_company` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_acquisition_execution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_acquisition_execution` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NULL DEFAULT NULL,
  `is_delivered` INT(11) NULL DEFAULT 0,
  `is_risk_contingency` INT(11) NULL DEFAULT 0,
  `value` FLOAT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `reference_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROJECT_AQC_EXE` (`project_id` ASC) VISIBLE,
  CONSTRAINT `FK_PROJECT_AQC_EXE`
    FOREIGN KEY (`project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_acquisition_planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_acquisition_planning` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NULL DEFAULT NULL,
  `items_to_be_acquired` TEXT NULL DEFAULT NULL,
  `contract_type` TEXT NULL DEFAULT NULL,
  `documents_to_acquisition` TEXT NULL DEFAULT NULL,
  `criteria_for_supplier_selection` TEXT NULL DEFAULT NULL,
  `additional_requirements` TEXT NULL DEFAULT NULL,
  `supplier_management_process` TEXT NULL DEFAULT NULL,
  `acquisition_roles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROJECT_QUALITY` (`project_id` ASC) VISIBLE,
  CONSTRAINT `FK_PROJECT_QUALITY`
    FOREIGN KEY (`project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_acquisition_planning_criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_acquisition_planning_criteria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `acquisition_id` INT(11) NULL DEFAULT NULL,
  `criteria` TEXT NULL DEFAULT NULL,
  `weight` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ACQUISITION_CRITERIA` (`acquisition_id` ASC) VISIBLE,
  CONSTRAINT `FK_ACQUISITION_CRITERIA`
    FOREIGN KEY (`acquisition_id`)
    REFERENCES `dbdotproject_g6`.`dotp_acquisition_planning` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_acquisition_planning_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_acquisition_planning_requirements` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `acquisition_id` INT(11) NULL DEFAULT NULL,
  `requirement` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_AQUISITION_REQUIREMENT` (`acquisition_id` ASC) VISIBLE,
  CONSTRAINT `FK_AQUISITION_REQUIREMENT`
    FOREIGN KEY (`acquisition_id`)
    REFERENCES `dbdotproject_g6`.`dotp_acquisition_planning` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_acquisition_planning_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_acquisition_planning_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `acquisition_id` INT(11) NULL DEFAULT NULL,
  `role` TEXT NULL DEFAULT NULL,
  `responsability` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ACQUISITION_ROLE` (`acquisition_id` ASC) VISIBLE,
  CONSTRAINT `FK_ACQUISITION_ROLE`
    FOREIGN KEY (`acquisition_id`)
    REFERENCES `dbdotproject_g6`.`dotp_acquisition_planning` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_billingcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_billingcode` (
  `billingcode_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `billingcode_name` VARCHAR(25) NOT NULL DEFAULT '',
  `billingcode_value` FLOAT NOT NULL DEFAULT 0,
  `billingcode_desc` VARCHAR(255) NOT NULL DEFAULT '',
  `billingcode_status` INT(1) NOT NULL DEFAULT 0,
  `company_id` BIGINT(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`billingcode_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_budget` (
  `budget_id` INT(11) NOT NULL AUTO_INCREMENT,
  `budget_project_id` INT(11) NOT NULL,
  `budget_reserve_management` DECIMAL(9,2) NOT NULL,
  `budget_sub_total` DECIMAL(9,2) NOT NULL,
  `budget_total` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`budget_id`),
  INDEX `fk_budget_project_id` (`budget_project_id` ASC) VISIBLE,
  CONSTRAINT `fk_budget_project_id`
    FOREIGN KEY (`budget_project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_budget_reserve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_budget_reserve` (
  `budget_reserve_id` INT(11) NOT NULL AUTO_INCREMENT,
  `budget_reserve_project_id` INT(11) NOT NULL,
  `budget_reserve_risk_id` INT(11) NOT NULL,
  `budget_reserve_description` VARCHAR(250) NULL DEFAULT NULL,
  `budget_reserve_financial_impact` INT(11) NULL DEFAULT NULL,
  `budget_reserve_inicial_month` DATETIME NULL DEFAULT NULL,
  `budget_reserve_final_month` DATETIME NULL DEFAULT NULL,
  `budget_reserve_value_total` DECIMAL(9,2) NULL DEFAULT NULL,
  PRIMARY KEY (`budget_reserve_id`),
  INDEX `fk_budget_reserve_project_id` (`budget_reserve_project_id` ASC) VISIBLE,
  CONSTRAINT `fk_budget_reserve_project_id`
    FOREIGN KEY (`budget_reserve_project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_common_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_common_notes` (
  `note_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `note_author` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `note_module` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `note_record_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `note_category` INT(3) UNSIGNED NOT NULL DEFAULT 0,
  `note_title` VARCHAR(100) NOT NULL DEFAULT '',
  `note_body` TEXT NOT NULL,
  `note_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `note_hours` FLOAT NOT NULL DEFAULT 0,
  `note_code` VARCHAR(8) NOT NULL DEFAULT '',
  `note_created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `note_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `note_modified_by` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`note_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_communication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_communication` (
  `communication_id` INT(11) NOT NULL AUTO_INCREMENT,
  `communication_title` VARCHAR(255) NOT NULL,
  `communication_information` VARCHAR(2000) NOT NULL,
  `communication_frequency_id` INT(11) NOT NULL,
  `communication_channel_id` INT(11) NOT NULL,
  `communication_project_id` INT(11) NOT NULL,
  `communication_restrictions` VARCHAR(2000) NOT NULL,
  `communication_date` VARCHAR(30) NOT NULL,
  `communication_responsible_authorization` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`communication_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_communication_channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_communication_channel` (
  `communication_channel_id` INT(11) NOT NULL AUTO_INCREMENT,
  `communication_channel` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`communication_channel_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_communication_frequency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_communication_frequency` (
  `communication_frequency_id` INT(11) NOT NULL AUTO_INCREMENT,
  `communication_frequency` VARCHAR(255) NOT NULL,
  `communication_frequency_hasdate` CHAR(3) NULL DEFAULT 'Nao',
  PRIMARY KEY (`communication_frequency_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_contacts` (
  `contact_id` INT(11) NOT NULL AUTO_INCREMENT,
  `contact_first_name` VARCHAR(30) NULL DEFAULT NULL,
  `contact_last_name` VARCHAR(30) NULL DEFAULT NULL,
  `contact_order_by` VARCHAR(30) NOT NULL DEFAULT '',
  `contact_title` VARCHAR(50) NULL DEFAULT NULL,
  `contact_birthday` DATE NULL DEFAULT NULL,
  `contact_job` VARCHAR(255) NULL DEFAULT NULL,
  `contact_company` VARCHAR(100) NOT NULL DEFAULT '',
  `contact_department` TINYTEXT NULL DEFAULT NULL,
  `contact_type` VARCHAR(20) NULL DEFAULT NULL,
  `contact_email` VARCHAR(255) NULL DEFAULT NULL,
  `contact_email2` VARCHAR(255) NULL DEFAULT NULL,
  `contact_url` VARCHAR(255) NULL DEFAULT NULL,
  `contact_phone` VARCHAR(30) NULL DEFAULT NULL,
  `contact_phone2` VARCHAR(30) NULL DEFAULT NULL,
  `contact_fax` VARCHAR(30) NULL DEFAULT NULL,
  `contact_mobile` VARCHAR(30) NULL DEFAULT NULL,
  `contact_address1` VARCHAR(60) NULL DEFAULT NULL,
  `contact_address2` VARCHAR(60) NULL DEFAULT NULL,
  `contact_city` VARCHAR(30) NULL DEFAULT NULL,
  `contact_state` VARCHAR(30) NULL DEFAULT NULL,
  `contact_zip` VARCHAR(11) NULL DEFAULT NULL,
  `contact_country` VARCHAR(30) NULL DEFAULT NULL,
  `contact_jabber` VARCHAR(255) NULL DEFAULT NULL,
  `contact_icq` VARCHAR(20) NULL DEFAULT NULL,
  `contact_msn` VARCHAR(255) NULL DEFAULT NULL,
  `contact_yahoo` VARCHAR(255) NULL DEFAULT NULL,
  `contact_aol` VARCHAR(30) NULL DEFAULT NULL,
  `contact_notes` TEXT NULL DEFAULT NULL,
  `contact_project` INT(11) NOT NULL DEFAULT 0,
  `contact_icon` VARCHAR(20) NULL DEFAULT 'obj/contact',
  `contact_owner` INT(10) UNSIGNED NULL DEFAULT 0,
  `contact_private` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`contact_id`),
  INDEX `idx_oby` (`contact_order_by` ASC) VISIBLE,
  INDEX `idx_co` (`contact_company` ASC) VISIBLE,
  INDEX `idx_prp` (`contact_project` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_communication_issuing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_communication_issuing` (
  `communication_issuing_id` INT(11) NOT NULL AUTO_INCREMENT,
  `communication_id` INT(11) NOT NULL,
  `communication_stakeholder_id` INT(11) NOT NULL,
  PRIMARY KEY (`communication_issuing_id`),
  INDEX `fk_communication_issuing` (`communication_stakeholder_id` ASC) VISIBLE,
  CONSTRAINT `fk_communication_issuing`
    FOREIGN KEY (`communication_stakeholder_id`)
    REFERENCES `dbdotproject_g6`.`dotp_contacts` (`contact_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_communication_receptor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_communication_receptor` (
  `communication_receptor_id` INT(11) NOT NULL AUTO_INCREMENT,
  `communication_id` INT(11) NOT NULL,
  `communication_stakeholder_id` INT(11) NOT NULL,
  PRIMARY KEY (`communication_receptor_id`),
  INDEX `fk_communication_receptor` (`communication_stakeholder_id` ASC) VISIBLE,
  CONSTRAINT `fk_communication_receptor`
    FOREIGN KEY (`communication_stakeholder_id`)
    REFERENCES `dbdotproject_g6`.`dotp_contacts` (`contact_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_companies` (
  `company_id` INT(10) NOT NULL AUTO_INCREMENT,
  `company_module` INT(10) NOT NULL DEFAULT 0,
  `company_name` VARCHAR(100) NULL DEFAULT '',
  `company_phone1` VARCHAR(30) NULL DEFAULT '',
  `company_phone2` VARCHAR(30) NULL DEFAULT '',
  `company_fax` VARCHAR(30) NULL DEFAULT '',
  `company_address1` VARCHAR(50) NULL DEFAULT '',
  `company_address2` VARCHAR(50) NULL DEFAULT '',
  `company_city` VARCHAR(30) NULL DEFAULT '',
  `company_state` VARCHAR(30) NULL DEFAULT '',
  `company_zip` VARCHAR(11) NULL DEFAULT '',
  `company_primary_url` VARCHAR(255) NULL DEFAULT '',
  `company_owner` INT(11) NOT NULL DEFAULT 0,
  `company_description` TEXT NULL DEFAULT NULL,
  `company_type` INT(3) NOT NULL DEFAULT 0,
  `company_email` VARCHAR(255) NULL DEFAULT NULL,
  `company_custom` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`company_id`),
  INDEX `idx_cpy1` (`company_owner` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_company_policies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_company_policies` (
  `company_policies_id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_policies_recognition` TEXT NULL DEFAULT NULL,
  `company_policies_policy` TEXT NULL DEFAULT NULL,
  `company_policies_safety` TEXT NULL DEFAULT NULL,
  `company_policies_company_id` INT(11) NOT NULL,
  PRIMARY KEY (`company_policies_id`),
  INDEX `company_policies_company_id` (`company_policies_company_id` ASC) VISIBLE,
  CONSTRAINT `dotp_company_policies_ibfk_1`
    FOREIGN KEY (`company_policies_company_id`)
    REFERENCES `dbdotproject_g6`.`dotp_companies` (`company_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_company_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_company_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  `role_name` TEXT NULL DEFAULT NULL,
  `identation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_company` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `dbdotproject_g6`.`dotp_companies` (`company_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_config` (
  `config_id` INT(11) NOT NULL AUTO_INCREMENT,
  `config_name` VARCHAR(255) NOT NULL DEFAULT '',
  `config_value` VARCHAR(255) NOT NULL DEFAULT '',
  `config_group` VARCHAR(255) NOT NULL DEFAULT '',
  `config_type` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`config_id`),
  UNIQUE INDEX `config_name` (`config_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 75
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_config_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_config_list` (
  `config_list_id` INT(11) NOT NULL AUTO_INCREMENT,
  `config_id` INT(11) NOT NULL DEFAULT 0,
  `config_list_name` VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`config_list_id`),
  INDEX `config_id` (`config_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_contact` INT(11) NOT NULL DEFAULT 0,
  `user_username` VARCHAR(255) NOT NULL DEFAULT '',
  `user_password` VARCHAR(32) NOT NULL DEFAULT '',
  `user_parent` INT(11) NOT NULL DEFAULT 0,
  `user_type` TINYINT(3) NOT NULL DEFAULT 0,
  `user_company` INT(11) NULL DEFAULT 0,
  `user_department` INT(11) NULL DEFAULT 0,
  `user_owner` INT(11) NOT NULL DEFAULT 0,
  `user_signature` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `idx_uid` (`user_username` ASC) VISIBLE,
  INDEX `idx_pwd` (`user_password` ASC) VISIBLE,
  INDEX `idx_user_parent` (`user_parent` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_human_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_human_resource` (
  `human_resource_id` INT(11) NOT NULL AUTO_INCREMENT,
  `human_resource_user_id` INT(11) NOT NULL,
  `human_resource_lattes_url` TEXT NULL DEFAULT NULL,
  `human_resource_mon` INT(11) NULL DEFAULT NULL,
  `human_resource_tue` INT(11) NULL DEFAULT NULL,
  `human_resource_wed` INT(11) NULL DEFAULT NULL,
  `human_resource_thu` INT(11) NULL DEFAULT NULL,
  `human_resource_fri` INT(11) NULL DEFAULT NULL,
  `human_resource_sat` INT(11) NULL DEFAULT NULL,
  `human_resource_sun` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`human_resource_id`),
  INDEX `human_resource_user_id` (`human_resource_user_id` ASC) VISIBLE,
  CONSTRAINT `dotp_human_resource_ibfk_1`
    FOREIGN KEY (`human_resource_user_id`)
    REFERENCES `dbdotproject_g6`.`dotp_users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_human_resources_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_human_resources_role` (
  `human_resources_role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `human_resources_role_name` TEXT NOT NULL,
  `human_resources_role_authority` TEXT NULL DEFAULT NULL,
  `human_resources_role_responsability` TEXT NULL DEFAULT NULL,
  `human_resources_role_competence` TEXT NULL DEFAULT NULL,
  `human_resources_role_company_id` INT(11) NOT NULL,
  PRIMARY KEY (`human_resources_role_id`),
  INDEX `human_resources_role_company_id` (`human_resources_role_company_id` ASC) VISIBLE,
  CONSTRAINT `dotp_human_resources_role_ibfk_1`
    FOREIGN KEY (`human_resources_role_company_id`)
    REFERENCES `dbdotproject_g6`.`dotp_companies` (`company_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_costs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_costs` (
  `cost_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cost_type_id` INT(11) NOT NULL,
  `cost_project_id` INT(11) NOT NULL,
  `cost_description` VARCHAR(150) NOT NULL,
  `cost_quantity` INT(11) NULL DEFAULT NULL,
  `cost_date_begin` DATETIME NULL DEFAULT NULL,
  `cost_date_end` DATETIME NULL DEFAULT NULL,
  `cost_value_unitary` DECIMAL(9,2) NULL DEFAULT NULL,
  `cost_value_total` DECIMAL(9,2) NULL DEFAULT NULL,
  `cost_human_resource_id` INT(11) NULL DEFAULT NULL,
  `cost_human_resource_role_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cost_id`),
  INDEX `fk_cost_project_id` (`cost_project_id` ASC) VISIBLE,
  INDEX `fk_cost_human_resource_role_id` (`cost_human_resource_role_id` ASC) VISIBLE,
  INDEX `fk_cost_human_resource_id` (`cost_human_resource_id` ASC) VISIBLE,
  CONSTRAINT `fk_cost_human_resource_id`
    FOREIGN KEY (`cost_human_resource_id`)
    REFERENCES `dbdotproject_g6`.`dotp_human_resource` (`human_resource_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cost_human_resource_role_id`
    FOREIGN KEY (`cost_human_resource_role_id`)
    REFERENCES `dbdotproject_g6`.`dotp_human_resources_role` (`human_resources_role_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cost_project_id`
    FOREIGN KEY (`cost_project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_custom_fields_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_custom_fields_lists` (
  `field_id` INT(11) NULL DEFAULT NULL,
  `list_option_id` INT(11) NULL DEFAULT NULL,
  `list_value` VARCHAR(250) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_custom_fields_struct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_custom_fields_struct` (
  `field_id` INT(11) NOT NULL,
  `field_module` VARCHAR(30) NULL DEFAULT NULL,
  `field_page` VARCHAR(30) NULL DEFAULT NULL,
  `field_htmltype` VARCHAR(20) NULL DEFAULT NULL,
  `field_datatype` VARCHAR(20) NULL DEFAULT NULL,
  `field_order` INT(11) NULL DEFAULT NULL,
  `field_name` VARCHAR(100) NULL DEFAULT NULL,
  `field_extratags` VARCHAR(250) NULL DEFAULT NULL,
  `field_description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`field_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_custom_fields_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_custom_fields_values` (
  `value_id` INT(11) NULL DEFAULT NULL,
  `value_module` VARCHAR(30) NULL DEFAULT NULL,
  `value_object_id` INT(11) NULL DEFAULT NULL,
  `value_field_id` INT(11) NULL DEFAULT NULL,
  `value_charvalue` VARCHAR(250) NULL DEFAULT NULL,
  `value_intvalue` INT(11) NULL DEFAULT NULL,
  INDEX `idx_cfv_id` (`value_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_departments` (
  `dept_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dept_parent` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `dept_company` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `dept_name` TINYTEXT NOT NULL,
  `dept_phone` VARCHAR(30) NULL DEFAULT NULL,
  `dept_fax` VARCHAR(30) NULL DEFAULT NULL,
  `dept_address1` VARCHAR(30) NULL DEFAULT NULL,
  `dept_address2` VARCHAR(30) NULL DEFAULT NULL,
  `dept_city` VARCHAR(30) NULL DEFAULT NULL,
  `dept_state` VARCHAR(30) NULL DEFAULT NULL,
  `dept_zip` VARCHAR(11) NULL DEFAULT NULL,
  `dept_url` VARCHAR(25) NULL DEFAULT NULL,
  `dept_desc` TEXT NULL DEFAULT NULL,
  `dept_owner` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Department heirarchy under a company';


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_dotpermissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_dotpermissions` (
  `acl_id` INT(11) NOT NULL DEFAULT 0,
  `user_id` VARCHAR(80) NOT NULL DEFAULT '',
  `section` VARCHAR(80) NOT NULL DEFAULT '',
  `axo` VARCHAR(80) NOT NULL DEFAULT '',
  `permission` VARCHAR(80) NOT NULL DEFAULT '',
  `allow` INT(11) NOT NULL DEFAULT 0,
  `priority` INT(11) NOT NULL DEFAULT 0,
  `enabled` INT(11) NOT NULL DEFAULT 0,
  INDEX `user_id` (`user_id` ASC, `section` ASC, `permission` ASC, `axo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_dpversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_dpversion` (
  `code_version` VARCHAR(10) NOT NULL DEFAULT '',
  `db_version` INT(11) NOT NULL DEFAULT 0,
  `last_db_update` DATE NOT NULL DEFAULT '0000-00-00',
  `last_code_update` DATE NOT NULL DEFAULT '0000-00-00')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_project_eap_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_project_eap_items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  `item_name` TEXT NULL DEFAULT NULL,
  `number` TEXT NULL DEFAULT NULL,
  `is_leaf` TEXT NULL DEFAULT NULL,
  `identation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eap_item_project` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_eap_item_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 183
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_eap_item_estimations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_eap_item_estimations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `eap_item_id` INT(11) NULL DEFAULT NULL,
  `size` FLOAT NULL DEFAULT NULL,
  `size_unit` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estimation_eap_item` (`eap_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_estimation_eap_item`
    FOREIGN KEY (`eap_item_id`)
    REFERENCES `dbdotproject_g6`.`dotp_project_eap_items` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 155
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_event_queue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_event_queue` (
  `queue_id` INT(11) NOT NULL AUTO_INCREMENT,
  `queue_start` INT(11) NOT NULL DEFAULT 0,
  `queue_type` VARCHAR(40) NOT NULL DEFAULT '',
  `queue_repeat_interval` INT(11) NOT NULL DEFAULT 0,
  `queue_repeat_count` INT(11) NOT NULL DEFAULT 0,
  `queue_data` LONGBLOB NOT NULL,
  `queue_callback` VARCHAR(127) NOT NULL DEFAULT '',
  `queue_owner` INT(11) NOT NULL DEFAULT 0,
  `queue_origin_id` INT(11) NOT NULL DEFAULT 0,
  `queue_module` VARCHAR(40) NOT NULL DEFAULT '',
  `queue_batched` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`queue_id`),
  INDEX `queue_start` (`queue_batched` ASC, `queue_start` ASC) VISIBLE,
  INDEX `queue_module` (`queue_module` ASC) VISIBLE,
  INDEX `queue_type` (`queue_type` ASC) VISIBLE,
  INDEX `queue_origin_id` (`queue_origin_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_events` (
  `event_id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_title` VARCHAR(255) NOT NULL DEFAULT '',
  `event_start_date` DATETIME NULL DEFAULT NULL,
  `event_end_date` DATETIME NULL DEFAULT NULL,
  `event_parent` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `event_description` TEXT NULL DEFAULT NULL,
  `event_times_recuring` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `event_recurs` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `event_remind` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `event_icon` VARCHAR(20) NULL DEFAULT 'obj/event',
  `event_owner` INT(11) NULL DEFAULT 0,
  `event_project` INT(11) NULL DEFAULT 0,
  `event_private` TINYINT(3) NULL DEFAULT 0,
  `event_type` TINYINT(3) NULL DEFAULT 0,
  `event_cwd` TINYINT(3) NULL DEFAULT 0,
  `event_notify` TINYINT(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`event_id`),
  INDEX `id_esd` (`event_start_date` ASC) VISIBLE,
  INDEX `id_eed` (`event_end_date` ASC) VISIBLE,
  INDEX `id_evp` (`event_parent` ASC) VISIBLE,
  INDEX `idx_ev1` (`event_owner` ASC) VISIBLE,
  INDEX `idx_ev2` (`event_project` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_file_folders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_file_folders` (
  `file_folder_id` INT(11) NOT NULL AUTO_INCREMENT,
  `file_folder_parent` INT(11) NOT NULL DEFAULT 0,
  `file_folder_name` VARCHAR(255) NOT NULL DEFAULT '',
  `file_folder_description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`file_folder_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_files` (
  `file_id` INT(11) NOT NULL AUTO_INCREMENT,
  `file_real_filename` VARCHAR(255) NOT NULL DEFAULT '',
  `file_folder` INT(11) NOT NULL DEFAULT 0,
  `file_project` INT(11) NOT NULL DEFAULT 0,
  `file_task` INT(11) NOT NULL DEFAULT 0,
  `file_name` VARCHAR(255) NOT NULL DEFAULT '',
  `file_parent` INT(11) NULL DEFAULT 0,
  `file_description` TEXT NULL DEFAULT NULL,
  `file_type` VARCHAR(100) NULL DEFAULT NULL,
  `file_owner` INT(11) NULL DEFAULT 0,
  `file_date` DATETIME NULL DEFAULT NULL,
  `file_size` INT(11) NULL DEFAULT 0,
  `file_version` FLOAT NOT NULL DEFAULT 0,
  `file_icon` VARCHAR(20) NULL DEFAULT 'obj/',
  `file_category` INT(11) NULL DEFAULT 0,
  `file_checkout` VARCHAR(255) NOT NULL DEFAULT '',
  `file_co_reason` TEXT NULL DEFAULT NULL,
  `file_version_id` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`file_id`),
  INDEX `idx_file_task` (`file_task` ASC) VISIBLE,
  INDEX `idx_file_project` (`file_project` ASC) VISIBLE,
  INDEX `idx_file_parent` (`file_parent` ASC) VISIBLE,
  INDEX `idx_file_vid` (`file_version_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_files_index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_files_index` (
  `file_id` INT(11) NOT NULL DEFAULT 0,
  `word` VARCHAR(50) NOT NULL DEFAULT '',
  `word_placement` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`file_id`, `word`, `word_placement`),
  INDEX `idx_fwrd` (`word` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_forum_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_forum_messages` (
  `message_id` INT(11) NOT NULL AUTO_INCREMENT,
  `message_forum` INT(11) NOT NULL DEFAULT 0,
  `message_parent` INT(11) NOT NULL DEFAULT 0,
  `message_author` INT(11) NOT NULL DEFAULT 0,
  `message_editor` INT(11) NOT NULL DEFAULT 0,
  `message_title` VARCHAR(255) NOT NULL DEFAULT '',
  `message_date` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `message_body` TEXT NULL DEFAULT NULL,
  `message_published` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`message_id`),
  INDEX `idx_mparent` (`message_parent` ASC) VISIBLE,
  INDEX `idx_mdate` (`message_date` ASC) VISIBLE,
  INDEX `idx_mforum` (`message_forum` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_forum_visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_forum_visits` (
  `visit_user` INT(10) NOT NULL DEFAULT 0,
  `visit_forum` INT(10) NOT NULL DEFAULT 0,
  `visit_message` INT(10) NOT NULL DEFAULT 0,
  `visit_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  INDEX `idx_fv` (`visit_user` ASC, `visit_forum` ASC, `visit_message` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_forum_watch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_forum_watch` (
  `watch_user` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `watch_forum` INT(10) UNSIGNED NULL DEFAULT NULL,
  `watch_topic` INT(10) UNSIGNED NULL DEFAULT NULL,
  INDEX `idx_fw1` (`watch_user` ASC, `watch_forum` ASC) VISIBLE,
  INDEX `idx_fw2` (`watch_user` ASC, `watch_topic` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Links users to the forums/messages they are watching';


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_forums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_forums` (
  `forum_id` INT(11) NOT NULL AUTO_INCREMENT,
  `forum_project` INT(11) NOT NULL DEFAULT 0,
  `forum_status` TINYINT(4) NOT NULL DEFAULT -1,
  `forum_owner` INT(11) NOT NULL DEFAULT 0,
  `forum_name` VARCHAR(50) NOT NULL DEFAULT '',
  `forum_create_date` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `forum_last_date` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `forum_last_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `forum_message_count` INT(11) NOT NULL DEFAULT 0,
  `forum_description` VARCHAR(255) NULL DEFAULT NULL,
  `forum_moderated` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`forum_id`),
  INDEX `idx_fproject` (`forum_project` ASC) VISIBLE,
  INDEX `idx_fowner` (`forum_owner` ASC) VISIBLE,
  INDEX `forum_status` (`forum_status` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_acl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_acl` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `section_value` VARCHAR(80) NOT NULL DEFAULT 'system',
  `allow` INT(11) NOT NULL DEFAULT 0,
  `enabled` INT(11) NOT NULL DEFAULT 0,
  `return_value` LONGTEXT NULL DEFAULT NULL,
  `note` LONGTEXT NULL DEFAULT NULL,
  `updated_date` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `gacl_enabled_acl` (`enabled` ASC) VISIBLE,
  INDEX `gacl_section_value_acl` (`section_value` ASC) VISIBLE,
  INDEX `gacl_updated_date_acl` (`updated_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_acl_sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_acl_sections` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  `order_value` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(230) NOT NULL DEFAULT '',
  `hidden` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gacl_value_acl_sections` (`value` ASC) VISIBLE,
  INDEX `gacl_hidden_acl_sections` (`hidden` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_acl_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_acl_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aco` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `section_value` VARCHAR(80) NOT NULL DEFAULT '0',
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  `order_value` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `hidden` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gacl_section_value_value_aco` (`section_value` ASC, `value` ASC) VISIBLE,
  INDEX `gacl_hidden_aco` (`hidden` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aco_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aco_map` (
  `acl_id` INT(11) NOT NULL DEFAULT 0,
  `section_value` VARCHAR(80) NOT NULL DEFAULT '0',
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  PRIMARY KEY (`acl_id`, `section_value`, `value`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aco_sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aco_sections` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  `order_value` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(230) NOT NULL DEFAULT '',
  `hidden` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gacl_value_aco_sections` (`value` ASC) VISIBLE,
  INDEX `gacl_hidden_aco_sections` (`hidden` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aco_sections_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aco_sections_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aco_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aco_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aro` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `section_value` VARCHAR(80) NOT NULL DEFAULT '0',
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  `order_value` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `hidden` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gacl_section_value_value_aro` (`section_value` ASC, `value` ASC) VISIBLE,
  INDEX `gacl_hidden_aro` (`hidden` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aro_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aro_groups` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `parent_id` INT(11) NOT NULL DEFAULT 0,
  `lft` INT(11) NOT NULL DEFAULT 0,
  `rgt` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`, `value`),
  INDEX `gacl_parent_id_aro_groups` (`parent_id` ASC) VISIBLE,
  INDEX `gacl_value_aro_groups` (`value` ASC) VISIBLE,
  INDEX `gacl_lft_rgt_aro_groups` (`lft` ASC, `rgt` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aro_groups_id_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aro_groups_id_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aro_groups_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aro_groups_map` (
  `acl_id` INT(11) NOT NULL DEFAULT 0,
  `group_id` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`acl_id`, `group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aro_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aro_map` (
  `acl_id` INT(11) NOT NULL DEFAULT 0,
  `section_value` VARCHAR(80) NOT NULL DEFAULT '0',
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  PRIMARY KEY (`acl_id`, `section_value`, `value`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aro_sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aro_sections` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  `order_value` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(230) NOT NULL DEFAULT '',
  `hidden` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gacl_value_aro_sections` (`value` ASC) VISIBLE,
  INDEX `gacl_hidden_aro_sections` (`hidden` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aro_sections_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aro_sections_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_aro_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_aro_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_axo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_axo` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `section_value` VARCHAR(80) NOT NULL DEFAULT '0',
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  `order_value` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `hidden` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gacl_section_value_value_axo` (`section_value` ASC, `value` ASC) VISIBLE,
  INDEX `gacl_hidden_axo` (`hidden` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_axo_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_axo_groups` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `parent_id` INT(11) NOT NULL DEFAULT 0,
  `lft` INT(11) NOT NULL DEFAULT 0,
  `rgt` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`, `value`),
  INDEX `gacl_parent_id_axo_groups` (`parent_id` ASC) VISIBLE,
  INDEX `gacl_value_axo_groups` (`value` ASC) VISIBLE,
  INDEX `gacl_lft_rgt_axo_groups` (`lft` ASC, `rgt` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_axo_groups_id_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_axo_groups_id_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_axo_groups_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_axo_groups_map` (
  `acl_id` INT(11) NOT NULL DEFAULT 0,
  `group_id` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`acl_id`, `group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_axo_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_axo_map` (
  `acl_id` INT(11) NOT NULL DEFAULT 0,
  `section_value` VARCHAR(80) NOT NULL DEFAULT '0',
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  PRIMARY KEY (`acl_id`, `section_value`, `value`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_axo_sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_axo_sections` (
  `id` INT(11) NOT NULL DEFAULT 0,
  `value` VARCHAR(80) NOT NULL DEFAULT '',
  `order_value` INT(11) NOT NULL DEFAULT 0,
  `name` VARCHAR(230) NOT NULL DEFAULT '',
  `hidden` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gacl_value_axo_sections` (`value` ASC) VISIBLE,
  INDEX `gacl_hidden_axo_sections` (`hidden` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_axo_sections_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_axo_sections_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_axo_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_axo_seq` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_groups_aro_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_groups_aro_map` (
  `group_id` INT(11) NOT NULL DEFAULT 0,
  `aro_id` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`group_id`, `aro_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_groups_axo_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_groups_axo_map` (
  `group_id` INT(11) NOT NULL DEFAULT 0,
  `axo_id` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`group_id`, `axo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_gacl_phpgacl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_gacl_phpgacl` (
  `name` VARCHAR(230) NOT NULL DEFAULT '',
  `value` VARCHAR(230) NOT NULL DEFAULT '',
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_tasks` (
  `task_id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(255) NULL DEFAULT NULL,
  `task_parent` INT(11) NULL DEFAULT 0,
  `task_milestone` TINYINT(1) NULL DEFAULT 0,
  `task_project` INT(11) NOT NULL DEFAULT 0,
  `task_owner` INT(11) NOT NULL DEFAULT 0,
  `task_start_date` DATETIME NULL DEFAULT NULL,
  `task_duration` FLOAT UNSIGNED NULL DEFAULT 0,
  `task_duration_type` INT(11) NOT NULL DEFAULT 1,
  `task_hours_worked` FLOAT UNSIGNED NULL DEFAULT 0,
  `task_end_date` DATETIME NULL DEFAULT NULL,
  `task_status` INT(11) NULL DEFAULT 0,
  `task_priority` TINYINT(4) NULL DEFAULT 0,
  `task_percent_complete` TINYINT(4) NULL DEFAULT 0,
  `task_description` TEXT NULL DEFAULT NULL,
  `task_target_budget` DECIMAL(10,2) NULL DEFAULT 0.00,
  `task_related_url` VARCHAR(255) NULL DEFAULT NULL,
  `task_creator` INT(11) NOT NULL DEFAULT 0,
  `task_order` INT(11) NOT NULL DEFAULT 0,
  `task_client_publish` TINYINT(1) NOT NULL DEFAULT 0,
  `task_dynamic` TINYINT(1) NOT NULL DEFAULT 0,
  `task_access` INT(11) NOT NULL DEFAULT 0,
  `task_notify` INT(11) NOT NULL DEFAULT 0,
  `task_departments` CHAR(100) NULL DEFAULT NULL,
  `task_contacts` CHAR(100) NULL DEFAULT NULL,
  `task_custom` LONGTEXT NULL DEFAULT NULL,
  `task_type` SMALLINT(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`task_id`),
  INDEX `idx_task_parent` (`task_parent` ASC) VISIBLE,
  INDEX `idx_task_project` (`task_project` ASC) VISIBLE,
  INDEX `idx_task_owner` (`task_owner` ASC) VISIBLE,
  INDEX `idx_task_order` (`task_order` ASC) VISIBLE,
  INDEX `idx_task1` (`task_start_date` ASC) VISIBLE,
  INDEX `idx_task2` (`task_end_date` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 128
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_project_tasks_estimated_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_project_tasks_estimated_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_id` INT(11) NULL DEFAULT NULL,
  `role_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estimation_task_roles` (`task_id` ASC) VISIBLE,
  INDEX `fk_estimation_roles` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_estimation_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `dbdotproject_g6`.`dotp_company_role` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_estimation_task_roles`
    FOREIGN KEY (`task_id`)
    REFERENCES `dbdotproject_g6`.`dotp_tasks` (`task_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 291
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_human_resource_allocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_human_resource_allocation` (
  `human_resource_allocation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_tasks_estimated_roles_id` INT(11) NOT NULL,
  `human_resource_id` INT(11) NOT NULL,
  PRIMARY KEY (`human_resource_allocation_id`),
  INDEX `human_resource_id` (`human_resource_id` ASC) VISIBLE,
  INDEX `project_tasks_estimated_roles_id` (`project_tasks_estimated_roles_id` ASC) VISIBLE,
  CONSTRAINT `dotp_human_resource_allocation_ibfk_1`
    FOREIGN KEY (`human_resource_id`)
    REFERENCES `dbdotproject_g6`.`dotp_human_resource` (`human_resource_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `dotp_human_resource_allocation_ibfk_2`
    FOREIGN KEY (`project_tasks_estimated_roles_id`)
    REFERENCES `dbdotproject_g6`.`dotp_project_tasks_estimated_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 197
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_human_resource_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_human_resource_roles` (
  `human_resource_roles_id` INT(11) NOT NULL AUTO_INCREMENT,
  `human_resources_role_id` INT(11) NOT NULL,
  `human_resource_id` INT(11) NOT NULL,
  PRIMARY KEY (`human_resource_roles_id`),
  INDEX `human_resources_role_id` (`human_resources_role_id` ASC) VISIBLE,
  INDEX `human_resource_id` (`human_resource_id` ASC) VISIBLE,
  CONSTRAINT `dotp_human_resource_roles_ibfk_1`
    FOREIGN KEY (`human_resources_role_id`)
    REFERENCES `dbdotproject_g6`.`dotp_human_resources_role` (`human_resources_role_id`)
    ON DELETE CASCADE,
  CONSTRAINT `dotp_human_resource_roles_ibfk_2`
    FOREIGN KEY (`human_resource_id`)
    REFERENCES `dbdotproject_g6`.`dotp_human_resource` (`human_resource_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_initiating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_initiating` (
  `initiating_id` INT(11) NOT NULL AUTO_INCREMENT,
  `initiating_title` VARCHAR(255) NOT NULL,
  `initiating_manager` INT(11) NOT NULL,
  `initiating_create_by` INT(11) NOT NULL,
  `initiating_date_create` DATETIME NOT NULL,
  `initiating_justification` TEXT NULL DEFAULT NULL,
  `initiating_objective` TEXT NULL DEFAULT NULL,
  `initiating_expected_result` TEXT NULL DEFAULT NULL,
  `initiating_premise` TEXT NULL DEFAULT NULL,
  `initiating_restrictions` TEXT NULL DEFAULT NULL,
  `initiating_budget` FLOAT NULL DEFAULT 0,
  `initiating_start_date` DATE NULL DEFAULT NULL,
  `initiating_end_date` DATE NULL DEFAULT NULL,
  `initiating_milestone` TEXT NULL DEFAULT NULL,
  `initiating_success` TEXT NULL DEFAULT NULL,
  `initiating_approved` INT(1) NULL DEFAULT 0,
  `initiating_authorized` INT(1) NULL DEFAULT 0,
  `initiating_completed` INT(1) NOT NULL DEFAULT 0,
  `initiating_approved_comments` TEXT NULL DEFAULT NULL,
  `initiating_authorized_comments` TEXT NULL DEFAULT NULL,
  `project_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`initiating_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_initiating_stakeholder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_initiating_stakeholder` (
  `initiating_stakeholder_id` INT(11) NOT NULL AUTO_INCREMENT,
  `initiating_id` INT(11) NOT NULL,
  `contact_id` INT(11) NOT NULL,
  `stakeholder_responsibility` VARCHAR(100) NULL DEFAULT NULL,
  `stakeholder_interest` VARCHAR(100) NULL DEFAULT NULL,
  `stakeholder_power` VARCHAR(100) NULL DEFAULT NULL,
  `stakeholder_strategy` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`initiating_stakeholder_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_modules` (
  `mod_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mod_name` VARCHAR(64) NOT NULL DEFAULT '',
  `mod_directory` VARCHAR(64) NOT NULL DEFAULT '',
  `mod_version` VARCHAR(10) NOT NULL DEFAULT '',
  `mod_setup_class` VARCHAR(64) NOT NULL DEFAULT '',
  `mod_type` VARCHAR(64) NOT NULL DEFAULT '',
  `mod_active` INT(1) UNSIGNED NOT NULL DEFAULT 0,
  `mod_ui_name` VARCHAR(20) NOT NULL DEFAULT '',
  `mod_ui_icon` VARCHAR(64) NOT NULL DEFAULT '',
  `mod_ui_order` TINYINT(3) NOT NULL DEFAULT 0,
  `mod_ui_active` INT(1) UNSIGNED NOT NULL DEFAULT 0,
  `mod_description` VARCHAR(255) NOT NULL DEFAULT '',
  `permissions_item_table` CHAR(100) NULL DEFAULT NULL,
  `permissions_item_field` CHAR(100) NULL DEFAULT NULL,
  `permissions_item_label` CHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`mod_id`, `mod_directory`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_baseline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_baseline` (
  `baseline_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `baseline_name` VARCHAR(255) NULL DEFAULT NULL,
  `baseline_version` VARCHAR(255) NULL DEFAULT NULL,
  `baseline_observation` TEXT NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `baseline_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`baseline_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_baseline_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_baseline_task` (
  `baseline_task_id` INT(11) NOT NULL AUTO_INCREMENT,
  `baseline_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `task_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `task_start_date` DATETIME NULL DEFAULT NULL,
  `task_duration` FLOAT UNSIGNED NULL DEFAULT 0,
  `task_duration_type` INT(11) NOT NULL DEFAULT 1,
  `task_hours_worked` FLOAT UNSIGNED NULL DEFAULT 0,
  `task_end_date` DATETIME NULL DEFAULT NULL,
  `task_percent_complete` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`baseline_task_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_baseline_task_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_baseline_task_log` (
  `baseline_task_id_log` INT(11) NOT NULL AUTO_INCREMENT,
  `baseline_task_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `task_log_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `task_log_creator` INT(11) NOT NULL DEFAULT 0,
  `task_log_hours` FLOAT NOT NULL DEFAULT 0,
  `task_log_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`baseline_task_id_log`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_baseline_user_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_baseline_user_cost` (
  `baseline_cost_id` INT(11) NOT NULL AUTO_INCREMENT,
  `baseline_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `cost_id` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `cost_value` DECIMAL(10,2) NULL DEFAULT 0.00,
  `cost_per_use` DECIMAL(11,0) NULL DEFAULT NULL,
  `cost_dt_begin` DATETIME NOT NULL,
  `cost_dt_end` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`baseline_cost_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_change_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_change_request` (
  `change_id` INT(10) NOT NULL AUTO_INCREMENT,
  `task_id` INT(10) NULL DEFAULT 0,
  `change_impact` INT(11) NOT NULL DEFAULT 0,
  `change_status` INT(11) NULL DEFAULT NULL,
  `change_description` TEXT NOT NULL,
  `change_cause` TEXT NOT NULL,
  `change_request` TEXT NOT NULL,
  `user_id` INT(10) NOT NULL DEFAULT 0,
  `change_date_limit` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `meeting_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `project_id` INT(10) NOT NULL,
  PRIMARY KEY (`change_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_meeting` (
  `meeting_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `dt_meeting_begin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `ds_title` TEXT NOT NULL,
  `ds_subject` TEXT NOT NULL,
  `dt_meeting_end` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `meeting_type_id` INT(10) NOT NULL,
  PRIMARY KEY (`meeting_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_meeting_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_meeting_item` (
  `meeting_item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `meeting_item_description` TEXT NULL DEFAULT NULL,
  `knownledge_area` TEXT NULL DEFAULT NULL,
  `language` TEXT NULL DEFAULT NULL,
  `item_order` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`meeting_item_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_meeting_item_select`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_meeting_item_select` (
  `meeting_item_select_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `meeting_item_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `meeting_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `status` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`meeting_item_select_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_meeting_item_senior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_meeting_item_senior` (
  `meeting_item_senior_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `meeting_percentual` DECIMAL(10,2) NULL DEFAULT 0.00,
  `meeting_size` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `meeting_idc` DECIMAL(10,2) NULL DEFAULT 0.00,
  `meeting_idp` DECIMAL(10,2) NULL DEFAULT 0.00,
  `meeting_vp` DECIMAL(10,2) NULL DEFAULT 0.00,
  `meeting_va` DECIMAL(10,2) NULL DEFAULT 0.00,
  `meeting_cr` DECIMAL(10,2) NULL DEFAULT 0.00,
  `meeting_baseline` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `meeting_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`meeting_item_senior_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_meeting_item_tasks_delivered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_meeting_item_tasks_delivered` (
  `meeting_item_taks_delivered_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `meeting_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`meeting_item_taks_delivered_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_meeting_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_meeting_type` (
  `meeting_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `meeting_type_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`meeting_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_meeting_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_meeting_user` (
  `meeting_user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `meeting_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`meeting_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_quality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_quality` (
  `quality_id` INT(11) NOT NULL AUTO_INCREMENT,
  `quality_type_id` INT(11) NOT NULL,
  `quality_description` TEXT NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `quality_status_id` INT(11) NOT NULL,
  `quality_date_end` DATETIME NULL DEFAULT NULL,
  `task_id` INT(11) NOT NULL,
  PRIMARY KEY (`quality_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_quality_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_quality_status` (
  `quality_status_id` INT(11) NOT NULL AUTO_INCREMENT,
  `quality_status_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`quality_status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_quality_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_quality_type` (
  `quality_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `quality_type_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`quality_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_responsibility_matriz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_responsibility_matriz` (
  `responsibility_id` INT(11) NOT NULL AUTO_INCREMENT,
  `responsibility_description` VARCHAR(255) NULL DEFAULT NULL,
  `responsibility_user_id_consultation` INT(11) NULL DEFAULT NULL,
  `responsibility_user_id_execut` INT(11) NULL DEFAULT NULL,
  `responsibility_user_id_support` INT(11) NULL DEFAULT NULL,
  `responsibility_user_id_approve` INT(11) NULL DEFAULT NULL,
  `project_id` INT(11) NOT NULL,
  PRIMARY KEY (`responsibility_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_monitoring_user_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_monitoring_user_cost` (
  `cost_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `cost_value` DECIMAL(10,2) NULL DEFAULT 0.00,
  `cost_per_use` DECIMAL(11,0) NULL DEFAULT NULL,
  `cost_dt_begin` DATETIME NOT NULL,
  `cost_dt_end` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`cost_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_need_for_training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_need_for_training` (
  `project_id` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  CONSTRAINT `FK_PROJECT_NEED_FOR_TRAINING`
    FOREIGN KEY (`project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_permissions` (
  `permission_id` INT(11) NOT NULL AUTO_INCREMENT,
  `permission_user` INT(11) NOT NULL DEFAULT 0,
  `permission_grant_on` VARCHAR(12) NOT NULL DEFAULT '',
  `permission_item` INT(11) NOT NULL DEFAULT 0,
  `permission_value` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`permission_id`),
  UNIQUE INDEX `idx_pgrant_on` (`permission_grant_on` ASC, `permission_item` ASC, `permission_user` ASC) VISIBLE,
  INDEX `idx_puser` (`permission_user` ASC) VISIBLE,
  INDEX `idx_pvalue` (`permission_value` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_post_mortem_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_post_mortem_analysis` (
  `pma_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(255) NOT NULL DEFAULT '',
  `project_start_date` DATETIME NULL DEFAULT NULL,
  `project_end_date` DATETIME NULL DEFAULT NULL,
  `project_planned_start_date` DATETIME NULL DEFAULT NULL,
  `project_planned_end_date` DATETIME NULL DEFAULT NULL,
  `project_meeting_date` DATETIME NULL DEFAULT NULL,
  `planned_budget` TEXT NULL DEFAULT NULL,
  `budget` TEXT NULL DEFAULT NULL,
  `participants` TEXT NULL DEFAULT NULL,
  `project_strength` TEXT NULL DEFAULT NULL,
  `project_weaknesses` TEXT NULL DEFAULT NULL,
  `improvement_suggestions` TEXT NULL DEFAULT NULL,
  `conclusions` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`pma_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_project_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_project_contacts` (
  `project_id` INT(10) NOT NULL,
  `contact_id` INT(10) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_project_departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_project_departments` (
  `project_id` INT(10) NOT NULL,
  `department_id` INT(10) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_project_ear_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_project_ear_items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  `item_name` TEXT NULL DEFAULT NULL,
  `number` TEXT NULL DEFAULT NULL,
  `is_leaf` TEXT NULL DEFAULT NULL,
  `identation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ear_item_project` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_ear_item_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_project_minutes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_project_minutes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NULL DEFAULT NULL,
  `minute_date` DATETIME NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `isEffort` INT(11) NULL DEFAULT 0,
  `isDuration` INT(11) NULL DEFAULT 0,
  `isResource` INT(11) NULL DEFAULT 0,
  `isSize` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_minute_project` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_minute_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_project_tasks_estimations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_project_tasks_estimations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_id` INT(11) NULL DEFAULT NULL,
  `effort` FLOAT NULL DEFAULT NULL,
  `effort_unit` TEXT NULL DEFAULT NULL,
  `duration` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estimation_task_attributes` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_estimation_task_attributes`
    FOREIGN KEY (`task_id`)
    REFERENCES `dbdotproject_g6`.`dotp_tasks` (`task_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 109
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_quality_planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_quality_planning` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NULL DEFAULT NULL,
  `quality_controlling` TEXT NULL DEFAULT NULL,
  `quality_assurance` TEXT NULL DEFAULT NULL,
  `quality_policies` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROJECT_ACQUISITION` (`project_id` ASC) VISIBLE,
  CONSTRAINT `FK_PROJECT_ACQUISITION`
    FOREIGN KEY (`project_id`)
    REFERENCES `dbdotproject_g6`.`dotp_projects` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_quality_assurance_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_quality_assurance_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quality_planning_id` INT(11) NULL DEFAULT NULL,
  `what` TEXT NULL DEFAULT NULL,
  `who` TEXT NULL DEFAULT NULL,
  `when` TEXT NULL DEFAULT NULL,
  `how` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROJECT_QUALITY_ASSURANCE_ITEM` (`quality_planning_id` ASC) VISIBLE,
  CONSTRAINT `FK_PROJECT_QUALITY_ASSURANCE_ITEM`
    FOREIGN KEY (`quality_planning_id`)
    REFERENCES `dbdotproject_g6`.`dotp_quality_planning` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_quality_control_goal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_quality_control_goal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quality_planning_id` INT(11) NULL DEFAULT NULL,
  `gqm_goal_object` TEXT NULL DEFAULT NULL,
  `gqm_goal_propose` TEXT NULL DEFAULT NULL,
  `gqm_goal_respect_to` TEXT NULL DEFAULT NULL,
  `gqm_goal_point_of_view` TEXT NULL DEFAULT NULL,
  `gqm_goal_context` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROJECT_QUALITY_CONTROL_GOAL` (`quality_planning_id` ASC) VISIBLE,
  CONSTRAINT `FK_PROJECT_QUALITY_CONTROL_GOAL`
    FOREIGN KEY (`quality_planning_id`)
    REFERENCES `dbdotproject_g6`.`dotp_quality_planning` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_quality_control_analiysis_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_quality_control_analiysis_question` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `goal_id` INT(11) NULL DEFAULT NULL,
  `question` TEXT NULL DEFAULT NULL,
  `target` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROJECT_QUALITY_GOAL_QUESTION` (`goal_id` ASC) VISIBLE,
  CONSTRAINT `FK_PROJECT_QUALITY_GOAL_QUESTION`
    FOREIGN KEY (`goal_id`)
    REFERENCES `dbdotproject_g6`.`dotp_quality_control_goal` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_quality_control_metric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_quality_control_metric` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) NULL DEFAULT NULL,
  `metric` TEXT NULL DEFAULT NULL,
  `how_to_collect` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROJECT_QUALITY_METRIC` (`question_id` ASC) VISIBLE,
  CONSTRAINT `FK_PROJECT_QUALITY_METRIC`
    FOREIGN KEY (`question_id`)
    REFERENCES `dbdotproject_g6`.`dotp_quality_control_analiysis_question` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_quality_control_requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_quality_control_requirement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quality_planning_id` INT(11) NULL DEFAULT NULL,
  `requirement` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROJECT_QUALITY_CONTROL_REQUIREMENT` (`quality_planning_id` ASC) VISIBLE,
  CONSTRAINT `FK_PROJECT_QUALITY_CONTROL_REQUIREMENT`
    FOREIGN KEY (`quality_planning_id`)
    REFERENCES `dbdotproject_g6`.`dotp_quality_planning` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_risks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_risks` (
  `risk_id` INT(11) NOT NULL AUTO_INCREMENT,
  `risk_name` VARCHAR(255) NOT NULL,
  `risk_cause` VARCHAR(255) NOT NULL,
  `risk_consequence` VARCHAR(255) NOT NULL,
  `risk_responsible` INT(11) NOT NULL,
  `risk_description` TEXT NULL DEFAULT NULL,
  `risk_probability` VARCHAR(15) NOT NULL,
  `risk_impact` VARCHAR(15) NOT NULL,
  `risk_answer_to_risk` TEXT NULL DEFAULT NULL,
  `risk_project` INT(11) NULL DEFAULT NULL,
  `risk_task` INT(11) NULL DEFAULT NULL,
  `risk_notes` TEXT NULL DEFAULT NULL,
  `risk_potential_other_projects` VARCHAR(2) NOT NULL,
  `risk_lessons_learned` TEXT NULL DEFAULT NULL,
  `risk_priority` VARCHAR(15) NOT NULL,
  `risk_active` INT(11) NOT NULL,
  `risk_strategy` INT(11) NOT NULL,
  `risk_prevention_actions` TEXT NULL DEFAULT NULL,
  `risk_contingency_plan` TEXT NULL DEFAULT NULL,
  `risk_period_start_date` DATE NULL DEFAULT NULL,
  `risk_period_end_date` DATE NULL DEFAULT NULL,
  `risk_status` VARCHAR(45) NULL DEFAULT NULL,
  `risk_ear_classification` VARCHAR(45) NULL DEFAULT NULL,
  `risk_triggers` TEXT NULL DEFAULT NULL,
  `risk_is_contingency` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`risk_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_risks_management_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_risks_management_plan` (
  `risk_plan_id` INT(11) NOT NULL DEFAULT 0,
  `project_id` INT(11) NULL DEFAULT NULL,
  `probability_super_low` VARCHAR(250) NULL DEFAULT NULL,
  `probability_low` VARCHAR(250) NULL DEFAULT NULL,
  `probability_medium` VARCHAR(250) NULL DEFAULT NULL,
  `probability_high` VARCHAR(250) NULL DEFAULT NULL,
  `probability_super_high` VARCHAR(250) NULL DEFAULT NULL,
  `impact_super_low` VARCHAR(250) NULL DEFAULT NULL,
  `impact_low` VARCHAR(250) NULL DEFAULT NULL,
  `impact_medium` VARCHAR(250) NULL DEFAULT NULL,
  `impact_high` VARCHAR(250) NULL DEFAULT NULL,
  `impact_super_high` VARCHAR(250) NULL DEFAULT NULL,
  `matrix_superlow_superlow` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superlow_low` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superlow_medium` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superlow_high` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superlow_superhigh` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_low_superlow` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_low_low` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_low_medium` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_low_high` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_low_superhigh` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_medium_superlow` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_medium_low` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_medium_medium` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_medium_high` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_medium_superhigh` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_high_superlow` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_high_low` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_high_medium` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_high_high` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_high_superhigh` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superhigh_superlow` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superhigh_low` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superhigh_medium` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superhigh_high` VARCHAR(30) NULL DEFAULT NULL,
  `matrix_superhigh_superhigh` VARCHAR(30) NULL DEFAULT NULL,
  `risk_contengency_reserve_protocol` VARCHAR(500) NULL DEFAULT NULL,
  `risk_revision_frequency` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`risk_plan_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_roles` (
  `role_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(24) NOT NULL DEFAULT '',
  `role_description` VARCHAR(255) NOT NULL DEFAULT '',
  `role_type` INT(3) UNSIGNED NOT NULL DEFAULT 0,
  `role_module` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_sessions` (
  `session_id` VARCHAR(60) NOT NULL DEFAULT '',
  `session_user` INT(11) NOT NULL DEFAULT 0,
  `session_data` LONGBLOB NULL DEFAULT NULL,
  `session_updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `session_created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`session_id`),
  INDEX `session_updated` (`session_updated` ASC) VISIBLE,
  INDEX `session_created` (`session_created` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_syskeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_syskeys` (
  `syskey_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `syskey_name` VARCHAR(48) NOT NULL DEFAULT '',
  `syskey_label` VARCHAR(255) NOT NULL DEFAULT '',
  `syskey_type` INT(1) UNSIGNED NOT NULL DEFAULT 0,
  `syskey_sep1` CHAR(2) NULL DEFAULT '\n',
  `syskey_sep2` CHAR(2) NOT NULL DEFAULT '|',
  PRIMARY KEY (`syskey_id`),
  UNIQUE INDEX `syskey_name` (`syskey_name` ASC) VISIBLE,
  UNIQUE INDEX `idx_syskey_name` (`syskey_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_sysvals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_sysvals` (
  `sysval_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sysval_key_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `sysval_title` VARCHAR(48) NOT NULL DEFAULT '',
  `sysval_value` TEXT NOT NULL,
  PRIMARY KEY (`sysval_id`),
  UNIQUE INDEX `idx_sysval_title` (`sysval_title` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_task_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_task_contacts` (
  `task_id` INT(10) NOT NULL,
  `contact_id` INT(10) NOT NULL,
  INDEX `idx_task_contacts` (`task_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_task_departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_task_departments` (
  `task_id` INT(10) NOT NULL,
  `department_id` INT(10) NOT NULL,
  INDEX `idx_task_departments` (`task_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_task_dependencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_task_dependencies` (
  `dependencies_task_id` INT(11) NOT NULL,
  `dependencies_req_task_id` INT(11) NOT NULL,
  PRIMARY KEY (`dependencies_task_id`, `dependencies_req_task_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_task_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_task_log` (
  `task_log_id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_log_task` INT(11) NOT NULL DEFAULT 0,
  `task_log_name` VARCHAR(255) NULL DEFAULT NULL,
  `task_log_description` TEXT NULL DEFAULT NULL,
  `task_log_creator` INT(11) NOT NULL DEFAULT 0,
  `task_log_hours` FLOAT NOT NULL DEFAULT 0,
  `task_log_date` DATETIME NULL DEFAULT NULL,
  `task_log_costcode` VARCHAR(8) NOT NULL DEFAULT '',
  `task_log_problem` TINYINT(1) NULL DEFAULT 0,
  `task_log_reference` TINYINT(4) NULL DEFAULT 0,
  `task_log_related_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`task_log_id`),
  INDEX `idx_log_task` (`task_log_task` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_task_minute_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_task_minute_members` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `task_minute_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_minute_partipant_task` (`task_minute_id` ASC) VISIBLE,
  INDEX `fk_task_minute_partipant_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_minute_partipant_task`
    FOREIGN KEY (`task_minute_id`)
    REFERENCES `dbdotproject_g6`.`dotp_project_minutes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_task_minute_partipant_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbdotproject_g6`.`dotp_contacts` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_tasks_mdp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_tasks_mdp` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_id` INT(11) NULL DEFAULT NULL,
  `pos_x` INT(11) NULL DEFAULT NULL,
  `pos_y` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mdp_task` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_mdp_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `dbdotproject_g6`.`dotp_tasks` (`task_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_tasks_workpackages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_tasks_workpackages` (
  `task_id` INT(11) NOT NULL DEFAULT 0,
  `eap_item_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`task_id`),
  CONSTRAINT `fk_task_eap_item`
    FOREIGN KEY (`task_id`)
    REFERENCES `dbdotproject_g6`.`dotp_tasks` (`task_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_tickets` (
  `ticket` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_company` INT(10) NOT NULL DEFAULT 0,
  `ticket_project` INT(10) NOT NULL DEFAULT 0,
  `author` VARCHAR(100) NOT NULL DEFAULT '',
  `recipient` VARCHAR(100) NOT NULL DEFAULT '',
  `subject` VARCHAR(100) NOT NULL DEFAULT '',
  `attachment` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `type` VARCHAR(15) NOT NULL DEFAULT '',
  `assignment` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `parent` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `activity` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `priority` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `cc` VARCHAR(255) NOT NULL DEFAULT '',
  `body` TEXT NOT NULL,
  `signature` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ticket`),
  INDEX `parent` (`parent` ASC) VISIBLE,
  INDEX `type` (`type` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_user_access_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_user_access_log` (
  `user_access_log_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `user_ip` VARCHAR(15) NOT NULL,
  `date_time_in` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `date_time_out` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `date_time_last_action` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`user_access_log_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 153
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_user_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_user_events` (
  `user_id` INT(11) NOT NULL DEFAULT 0,
  `event_id` INT(11) NOT NULL DEFAULT 0,
  INDEX `uek1` (`user_id` ASC, `event_id` ASC) VISIBLE,
  INDEX `uek2` (`event_id` ASC, `user_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_user_preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_user_preferences` (
  `pref_user` VARCHAR(12) NOT NULL DEFAULT '',
  `pref_name` VARCHAR(72) NOT NULL DEFAULT '',
  `pref_value` VARCHAR(32) NOT NULL DEFAULT '',
  INDEX `pref_user` (`pref_user` ASC, `pref_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_user_roles` (
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `role_id` INT(10) UNSIGNED NOT NULL DEFAULT 0)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_user_task_pin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_user_task_pin` (
  `user_id` INT(11) NOT NULL DEFAULT 0,
  `task_id` INT(10) NOT NULL DEFAULT 0,
  `task_pinned` TINYINT(2) NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`, `task_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_user_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_user_tasks` (
  `user_id` INT(11) NOT NULL DEFAULT 0,
  `user_type` TINYINT(4) NOT NULL DEFAULT 0,
  `task_id` INT(11) NOT NULL DEFAULT 0,
  `perc_assignment` INT(11) NOT NULL DEFAULT 100,
  `user_task_priority` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`user_id`, `task_id`),
  INDEX `user_type` (`user_type` ASC) VISIBLE,
  INDEX `idx_user_tasks` (`task_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbdotproject_g6`.`dotp_wbs_dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdotproject_g6`.`dotp_wbs_dictionary` (
  `wbs_item_id` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`wbs_item_id`),
  CONSTRAINT `FK_WBS_ITEM_DICTIONARY`
    FOREIGN KEY (`wbs_item_id`)
    REFERENCES `dbdotproject_g6`.`dotp_project_eap_items` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
